application:
  port: 8080

database:
  username: "postgres"
  password: 123456
  port: 5432
  host: "127.0.0.1"
  database_name:  "newsletter"

email_client:
  base_url: "http://127.0.0.1:8080"
  sender_email: "test@example.com"